//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImageBoard.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.comments1 = new HashSet<comment>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string username { get; set; }
        public int post_id { get; set; }
        public Nullable<int> comment_id { get; set; }
        public Nullable<bool> reply { get; set; }
        public string post { get; set; }
        public System.DateTime created_on { get; set; }
    
        public virtual user user { get; set; }
        public virtual post post1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comment> comments1 { get; set; }
        public virtual comment comment1 { get; set; }
    }
}
